### ISSUE TITLE
Duplicate variables in the module in EasyCrypt extraction

### ISSUE THREAD

**Issue by JoaoDiogoDuarte** [formosa-crypto/formosa-25519#14]
When performing the  EasyCrypt extraction using `make extract-to-easycrypt `, there are many duplicate variables which means that the EasyCrypt file is not valid. As an example, in the procedure, the first few lines in the `ref4` implementation are:

```
 proc __mul4_rsr (fs:W64.t Array4.t, g:W64.t Array4.t) : W64.t Array4.t = {

    var tmp___h: W64.t Array4.t;
    var tmp___h: W64.t Array4.t;
```
or in the `invert4` procedures

```
 proc __invert4 (fs:W64.t Array4.t) : W64.t Array4.t = {

    var tmp___xa: W64.t Array4.t;
    var tmp___ra: W64.t Array4.t;
    var tmp___x: W64.t Array4.t;
    var tmp___x: W64.t Array4.t;

```

I am using the Jasmin version with git hash `c41ad80`, but I checked that this problem persists in the latest stable release. If this issue is more appropriate to report on the jasmin repository, please do say!

**Comment by tfaoliveira-sb** [comment]
I'm not able to replicate the issue with this [Dockerfile](https://github.com/formosa-crypto/formosa-25519/blob/main/scripts/docker/Dockerfile).

I also cannot find in file [invert4.jinc](https://github.com/formosa-crypto/formosa-25519/blob/main/src/crypto_scalarmult/curve25519/amd64/ref4/invert4.jinc), from the `ref4` implementation, any variable name that matches `*xa*` or `*ra*` which suggests that this is not about the `ref4` implementation.

Can you take a look and, if possible/it makes sense, get back to me with a sequence of commands that allow me to replicate this issue on [Dockerfile](https://github.com/formosa-crypto/formosa-25519/blob/main/scripts/docker/Dockerfile) (or a variant of it by using a different Jasmin compiler version)?

In any case, you can also try to come up with a minimal example for this issue and report it [here](https://github.com/jasmin-lang/jasmin/issues/new).

**Comment by JoaoDiogoDuarte** [comment]
Strange, I'll give it a go with the Dockerfile and post my findings soon :). If I manage to replicate it I'll come up with a minimal working example and the commands for you to use with the Dockerfile.

**Comment by JoaoDiogoDuarte** [comment]
No issue, I had an old or edited jasmin compiler which caused the error. Closing the issue as this was a me problem.
