### ISSUE TITLE
Deploy first version of CI - amd64, linux

### ISSUE THREAD

**Issue by tfaoliveira-sb** [formosa-crypto/formosa-25519#3]
The goal for the first version of CI (amd64; linux) is the following:
- [x] src/: safety checks; sct; extraction to EasyCrypt; compilation from Jasmin to assembly ~(-ATT and -intel)~ (will be addressed separately)
- [x] test/: checksums and valgrind
- [x] bench/: for a reduced number of timings, check if compilation is possible
- [x] proof/: extracted files are processed by EasyCrypt

Note: Functional correctness proofs will be handled in a separate issue.

**Comment by tfaoliveira** [comment]
https://github.com/formosa-crypto/formosa-25519/commit/2cd0a8cbc2e58f3aa395b2cea5e9d2adb6775e73
