### ISSUE TITLE
stack zeroization

### ISSUE THREAD

**Issue by tfaoliveira-sb** [formosa-crypto/formosa-25519#5]
Integrate stack zeroization:
- [x] Benchmarks: comparing how the code performs with the available options; Available to the user/dev;
- [x] CI coverage: compiling the code with the corresponding compiler option and check testing results;
- [x] Compilation flag should be enabled by default when producing the lib, but it should be possible to disable via Makefile arguments / command line

Related publication: https://eprint.iacr.org/2023/1713

**Comment by tfaoliveira** [comment]
with -stack-zero loopSCT, less than 200 cycles overhead;
set as default
